# Generated by Django 6.0.3 on 2026-03-18 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('profile_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('help_numerator', models.PositiveIntegerField(default=0)),
                ('help_denominator', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review_time', models.DateTimeField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='productapp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='productapp.product')),
            ],
            options={
                'ordering': ['-review_time'],
                'indexes': [models.Index(fields=['product'], name='productapp__product_479c48_idx'), models.Index(fields=['customer'], name='productapp__custome_e4e1dc_idx'), models.Index(fields=['score'], name='productapp__score_ce6aa7_idx'), models.Index(fields=['review_time'], name='productapp__review__c7e6e4_idx')],
            },
        ),
    ]
